import { act, cleanup, renderHook } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { I18nProvider } from '../../i18n';
import { useFocusSessionController } from './useFocusSessionController';

vi.mock('../../services/activity.service', () => ({ createActivity: vi.fn().mockResolvedValue(undefined) }));
vi.mock('../../services/focusSession.service', () => ({ fetchDailyFocusStats: vi.fn(), logFocusSession: vi.fn() }));
vi.mock('../../components/organisms/toast/notify', () => ({ notify: { info: vi.fn(), success: vi.fn() } }));
beforeEach(() => localStorage.clear());
afterEach(() => { cleanup(); vi.useRealTimers(); });
const summary = (id: string) => ({ id, title: id, boardId: 'board', boardTitle: 'Project', dueDate: null, priority: null });
it('starts, counts down, pauses and resumes without a task or launch modal', () => {
  vi.useFakeTimers();
  const { result } = renderHook(() => useFocusSessionController({ user: null, workspaceId: 'workspace', boardData: { columns: [], task: {}, list: {} }, activeBoardId: null, activeBoardSummary: null }), { wrapper: I18nProvider });
  act(() => result.current.handleStartFocusTimer());
  expect(result.current.timerState.isRunning).toBe(true);
  expect(result.current.timerState.activeTaskId).toBeNull();
  expect(result.current.focusTasks).toHaveLength(0);
  expect(result.current.focusLaunchTask).toBeNull();
  const sessionId = result.current.timerState.sessionId;
  act(() => vi.advanceTimersByTime(5000));
  expect(result.current.remainingSeconds).toBe(1495);
  act(() => result.current.pauseTimer());
  expect(result.current.timerState.isRunning).toBe(false);
  act(() => result.current.startFocusSessionNow());
  expect(result.current.timerState.isRunning).toBe(true);
  expect(result.current.timerState.sessionId).toBe(sessionId);
  expect(result.current.remainingSeconds).toBe(1495);
  act(() => result.current.resetTimer());
  expect(result.current.remainingSeconds).toBe(1500);
  expect(result.current.timerState.isRunning).toBe(false);
});
it.each(['shortBreak', 'longBreak'] as const)('starts %s without requiring a focused task', (mode) => {
  const { result } = renderHook(() => useFocusSessionController({ user: null, workspaceId: 'workspace', boardData: { columns: [], task: {}, list: {} }, activeBoardId: null, activeBoardSummary: null }), { wrapper: I18nProvider });
  act(() => result.current.setMode(mode));
  act(() => result.current.handleStartFocusTimer());
  expect(result.current.timerState.isRunning).toBe(true);
  expect(result.current.timerState.mode).toBe(mode);
  expect(result.current.timerState.activeTaskId).toBeNull();
});
it('prefills a reviewed AI step without starting the timer before confirmation', () => {
  const { result } = renderHook(() => useFocusSessionController({ user: null, workspaceId: 'workspace', boardData: { columns: [], task: {}, list: {} }, activeBoardId: null, activeBoardSummary: null }), { wrapper: I18nProvider });
  act(() => result.current.setMode('shortBreak'));
  act(() => result.current.handleStartFocusTaskFromHome(summary('mission'), 'Open the research notes'));
  expect(result.current.timerState.mode).toBe('focus');
  expect(result.current.focusLaunchIntention).toBe('Open the research notes');
  expect(result.current.timerState.isRunning).toBe(false);
  act(() => result.current.confirmFocusLaunch('Read the notes and mark three findings'));
  expect(result.current.activeFocusIntention).toEqual({ taskId: 'mission', text: 'Read the notes and mark three findings' });
  expect(result.current.timerState.isRunning).toBe(true);
});
it('requires an intention for a different task and enforces the Home pin limit', () => {
  const { result } = renderHook(() => useFocusSessionController({ user: null, workspaceId: 'workspace', boardData: { columns: [], task: {}, list: {} }, activeBoardId: null, activeBoardSummary: null }), { wrapper: I18nProvider });
  act(() => result.current.handleStartFocusTaskFromHome(summary('a')));
  expect(result.current.focusLaunchTask?.id).toBe('a');
  expect(result.current.timerState.isRunning).toBe(false);
  act(() => result.current.confirmFocusLaunch('Write introduction'));
  expect(result.current.timerState.isRunning).toBe(true);
  act(() => result.current.pauseTimer());
  act(() => result.current.handleStartFocusTaskFromHome(summary('a')));
  expect(result.current.focusLaunchTask).toBeNull();
  expect(result.current.activeFocusIntention?.text).toBe('Write introduction');
  act(() => result.current.handleStartFocusTaskFromHome(summary('b')));
  expect(result.current.timerState.isRunning).toBe(false);
  expect(result.current.focusLaunchTask?.id).toBe('b');
  act(() => result.current.confirmFocusLaunch('Review draft'));
  expect(result.current.activeFocusIntention).toEqual({ taskId: 'b', text: 'Review draft' });
  act(() => result.current.handleToggleFocusTaskFromHome(summary('c')));
  act(() => result.current.handleStartFocusTaskFromHome(summary('d')));
  expect(result.current.focusTasks).toHaveLength(3);
  expect(result.current.timerState.activeTaskId).toBe('b');
  expect(result.current.timerState.isRunning).toBe(true);
});
