import type { ArcanaCardData } from './types';

// The 22 Major Arcana, mapped to the DX-Tarots "major" atlas (10x6, ids 0-21
// in standard Major Arcana order). Bilingual, original reflective content.
export const arcanaMajorCards: ArcanaCardData[] = [
  {
    id: 'the-fool',
    atlas: 'major',
    atlasIndex: 0,
    group: 'major',
    name: { en: 'The Fool', vi: 'Gã Khờ' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#f8d477',
    keywords: { en: ['beginnings', 'freedom', 'trust'], vi: ['khởi đầu', 'tự do', 'niềm tin'] },
    meaning: {
      en: 'The Fool carries the bright uncertainty of a first step — innocence, light courage, and the moment before experience hardens into fear.',
      vi: 'Gã Khờ mang trong mình sự háo hức trong trẻo của bước chân đầu tiên: nét hồn nhiên, lòng dũng cảm nhẹ nhõm và khoảnh khắc trước khi va vấp biến thành nỗi sợ.',
    },
    reversedKeywords: { en: ['recklessness', 'hesitation', 'unpreparedness'], vi: ['liều lĩnh', 'chần chừ', 'chưa sẵn sàng'] },
    reversedMeaning: {
      en: 'Reversed, The Fool warns of rushing in without thought, or of fear keeping you from a step worth taking.',
      vi: 'Khi ngược, Gã Khờ nhắc bạn coi chừng sự hấp tấp thiếu suy xét, hoặc nỗi sợ đang giữ chân bạn trước một bước đáng để thử.',
    },
  },
  {
    id: 'the-magician',
    atlas: 'major',
    atlasIndex: 1,
    group: 'major',
    name: { en: 'The Magician', vi: 'Nhà Ảo Thuật' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#d9b8ff',
    keywords: { en: ['willpower', 'skill', 'manifestation'], vi: ['ý chí', 'tài năng', 'hiện thực hóa'] },
    meaning: {
      en: 'The Magician speaks of focused will and the tools already in hand. The abstract can take shape when intention, timing, and action meet.',
      vi: 'Nhà Ảo Thuật nói về ý chí tập trung và những công cụ vốn đã nằm trong tay bạn. Điều còn mơ hồ có thể thành hình khi ý định, thời điểm và hành động gặp nhau.',
    },
    reversedKeywords: { en: ['scattered focus', 'self-doubt', 'untapped potential'], vi: ['phân tán', 'hoài nghi bản thân', 'tiềm năng bỏ ngỏ'] },
    reversedMeaning: {
      en: 'Reversed, it points to scattered energy or talent used in the wrong place. Gather yourself around one clear aim.',
      vi: 'Khi ngược, lá bài cho thấy năng lượng đang bị dàn trải hoặc tài năng dùng chưa đúng chỗ. Hãy thu mình lại quanh một mục tiêu rõ ràng.',
    },
  },
  {
    id: 'the-high-priestess',
    atlas: 'major',
    atlasIndex: 2,
    group: 'major',
    name: { en: 'The High Priestess', vi: 'Nữ Tư Tế' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#a7c7ff',
    keywords: { en: ['intuition', 'mystery', 'listening'], vi: ['trực giác', 'điều bí ẩn', 'lắng nghe'] },
    meaning: {
      en: 'The High Priestess invites quiet listening. Not every answer is visible yet, but a deeper current is already moving beneath the surface.',
      vi: 'Nữ Tư Tế mời bạn lắng nghe trong tĩnh lặng. Chưa phải câu trả lời nào cũng hiện rõ, nhưng một dòng chảy sâu hơn đã bắt đầu chuyển động dưới bề mặt.',
    },
    reversedKeywords: { en: ['ignored intuition', 'inner noise', 'secrets'], vi: ['phớt lờ trực giác', 'tâm trí ồn ào', 'điều giấu kín'] },
    reversedMeaning: {
      en: 'Reversed, you may be drowning your inner voice in outside noise. A moment of stillness can return clarity.',
      vi: 'Khi ngược, có thể bạn đang để tiếng ồn bên ngoài lấn át tiếng nói bên trong. Một khoảng lặng có thể trả lại cho bạn sự sáng rõ.',
    },
  },
  {
    id: 'the-empress',
    atlas: 'major',
    atlasIndex: 3,
    group: 'major',
    name: { en: 'The Empress', vi: 'Nữ Hoàng' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#ffb7cf',
    keywords: { en: ['growth', 'nurture', 'abundance'], vi: ['nuôi dưỡng', 'chăm sóc', 'sung túc'] },
    meaning: {
      en: 'The Empress is warmth, nourishment, and natural growth. She favors patience, beauty, and steady tending of what wants to bloom.',
      vi: 'Nữ Hoàng tượng trưng cho sự ấm áp, nuôi dưỡng và phát triển tự nhiên. Lá bài ưu ái sự kiên nhẫn, cái đẹp và việc chăm chút đều đặn cho điều đang muốn nở hoa.',
    },
    reversedKeywords: { en: ['depletion', 'self-neglect', 'stagnation'], vi: ['cạn kiệt', 'bỏ quên bản thân', 'trì trệ'] },
    reversedMeaning: {
      en: 'Reversed, she reminds you that you are giving more than you receive. Nourish yourself before tending to others.',
      vi: 'Khi ngược, Nữ Hoàng nhắc rằng bạn đang cho đi nhiều hơn nhận lại. Hãy bồi đắp cho chính mình trước khi tiếp tục chăm lo cho người khác.',
    },
  },
  {
    id: 'the-emperor',
    atlas: 'major',
    atlasIndex: 4,
    group: 'major',
    name: { en: 'The Emperor', vi: 'Hoàng Đế' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#ff9b7a',
    keywords: { en: ['structure', 'stability', 'authority'], vi: ['kỷ cương', 'vững vàng', 'quyền uy'] },
    meaning: {
      en: 'The Emperor speaks of order, boundaries, and a solid foundation. He favors building a clear framework so everything has its place.',
      vi: 'Hoàng Đế nói về trật tự, ranh giới và một nền móng vững chắc. Lá bài khuyến khích dựng nên khuôn khổ rõ ràng để mọi thứ có chỗ đứng của mình.',
    },
    reversedKeywords: { en: ['rigidity', 'over-control', 'lack of direction'], vi: ['cứng nhắc', 'kiểm soát thái quá', 'mất phương hướng'] },
    reversedMeaning: {
      en: 'Reversed, it warns of rigidity or over-control — or, conversely, a lack of needed discipline. Find the middle.',
      vi: 'Khi ngược, lá bài cảnh báo sự cứng nhắc hay kiểm soát quá mức, hoặc ngược lại là thiếu đi kỷ luật cần thiết. Hãy tìm lại điểm cân bằng.',
    },
  },
  {
    id: 'the-hierophant',
    atlas: 'major',
    atlasIndex: 5,
    group: 'major',
    name: { en: 'The Hierophant', vi: 'Giáo Hoàng' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#e7d6a8',
    keywords: { en: ['tradition', 'learning', 'guidance'], vi: ['truyền thống', 'học hỏi', 'dẫn dắt'] },
    meaning: {
      en: 'The Hierophant points to inherited knowledge, shared values, and guidance from those who walked the path before you.',
      vi: 'Giáo Hoàng chỉ về tri thức được trao truyền, những giá trị chung và sự dẫn dắt từ những người đã đi trước bạn.',
    },
    reversedKeywords: { en: ['breaking convention', 'free thinking', 'doubt'], vi: ['phá lệ', 'tư duy tự do', 'hoài nghi'] },
    reversedMeaning: {
      en: 'Reversed, it encourages you to find your own path, question the rules, and trust your own understanding.',
      vi: 'Khi ngược, lá bài khích lệ bạn tìm lối đi riêng, dám đặt câu hỏi với quy ước và tin vào cách hiểu của chính mình.',
    },
  },
  {
    id: 'the-lovers',
    atlas: 'major',
    atlasIndex: 6,
    group: 'major',
    name: { en: 'The Lovers', vi: 'Tình Nhân' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#ffa6c9',
    keywords: { en: ['connection', 'choice', 'harmony'], vi: ['gắn kết', 'lựa chọn', 'hòa hợp'] },
    meaning: {
      en: 'The Lovers speak of deep connection and choices made from true values. Choose what resonates with who you really are.',
      vi: 'Tình Nhân nói về sự gắn kết sâu sắc và những lựa chọn xuất phát từ giá trị thật. Hãy chọn điều cộng hưởng với con người thật của bạn.',
    },
    reversedKeywords: { en: ['misalignment', 'conflict', 'indecision'], vi: ['lệch nhịp', 'mâu thuẫn', 'lưỡng lự'] },
    reversedMeaning: {
      en: 'Reversed, it shows a clash of values or a decision pulling you in two. Be honest about what you truly want.',
      vi: 'Khi ngược, lá bài cho thấy sự lệch pha trong giá trị hoặc một quyết định đang giằng xé bạn. Hãy thành thật với điều mình thực sự muốn.',
    },
  },
  {
    id: 'the-chariot',
    atlas: 'major',
    atlasIndex: 7,
    group: 'major',
    name: { en: 'The Chariot', vi: 'Cỗ Xe' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#9bdcff',
    keywords: { en: ['direction', 'discipline', 'momentum'], vi: ['phương hướng', 'kỷ luật', 'đà tiến'] },
    meaning: {
      en: 'The Chariot points to movement with purpose. Progress comes from choosing a direction, holding the reins, and pressing through resistance.',
      vi: 'Cỗ Xe chỉ về sự chuyển động có chủ đích. Tiến bộ đến từ việc chọn một hướng đi, giữ chắc dây cương và bền bỉ vượt qua trở lực.',
    },
    reversedKeywords: { en: ['losing control', 'distraction', 'stalling'], vi: ['mất lái', 'xao nhãng', 'chững lại'] },
    reversedMeaning: {
      en: 'Reversed, it suggests feeling out of control or pulled in many directions at once. Recommit to a single course.',
      vi: 'Khi ngược, lá bài gợi cảm giác mất kiểm soát hoặc bị kéo về nhiều phía cùng lúc. Hãy chọn lại một hướng đi duy nhất.',
    },
  },
  {
    id: 'strength',
    atlas: 'major',
    atlasIndex: 8,
    group: 'major',
    name: { en: 'Strength', vi: 'Sức Mạnh' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#ffd36f',
    keywords: { en: ['courage', 'patience', 'self-mastery'], vi: ['can đảm', 'kiên nhẫn', 'làm chủ bản thân'] },
    meaning: {
      en: 'Strength is quiet courage rather than force — emotional steadiness, compassion, and meeting intensity without turning harsh.',
      vi: 'Sức Mạnh là lòng can đảm trầm lặng chứ không phải sự áp chế: là sự vững vàng trong cảm xúc, lòng trắc ẩn và khả năng đối diện sóng gió mà không trở nên gay gắt.',
    },
    reversedKeywords: { en: ['self-doubt', 'burnout', 'impatience'], vi: ['nghi ngờ bản thân', 'kiệt sức', 'nóng vội'] },
    reversedMeaning: {
      en: 'Reversed, it speaks of inner fatigue or a temper hard to hold. Be gentler with yourself.',
      vi: 'Khi ngược, lá bài nói về sự mệt mỏi bên trong hoặc cơn nóng giận khó kìm nén. Hãy dịu dàng hơn với chính mình.',
    },
  },
  {
    id: 'the-hermit',
    atlas: 'major',
    atlasIndex: 9,
    group: 'major',
    name: { en: 'The Hermit', vi: 'Ẩn Sĩ' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#d8e2ff',
    keywords: { en: ['solitude', 'wisdom', 'discernment'], vi: ['tĩnh lặng', 'minh triết', 'sáng suốt'] },
    meaning: {
      en: 'The Hermit turns inward to find a truer light, favoring reflection, distance from noise, and insight that arrives when you stop performing certainty.',
      vi: 'Ẩn Sĩ hướng vào bên trong để tìm một thứ ánh sáng chân thật hơn, đề cao sự chiêm nghiệm, rời xa ồn ào và loại hiểu biết chỉ đến khi bạn thôi tỏ ra chắc chắn.',
    },
    reversedKeywords: { en: ['isolation', 'avoidance', 'feeling lost'], vi: ['cô lập', 'né tránh', 'lạc lối'] },
    reversedMeaning: {
      en: 'Reversed, it warns that withdrawing too far becomes isolation. Sometimes the answer is to reconnect.',
      vi: 'Khi ngược, lá bài cảnh báo rằng rút lui quá xa sẽ thành cô lập. Đôi khi câu trả lời lại nằm ở việc mở lòng kết nối trở lại.',
    },
  },
  {
    id: 'wheel-of-fortune',
    atlas: 'major',
    atlasIndex: 10,
    group: 'major',
    name: { en: 'Wheel of Fortune', vi: 'Bánh Xe Số Phận' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#f7b955',
    keywords: { en: ['cycles', 'chance', 'turning point'], vi: ['vòng xoay', 'cơ duyên', 'bước ngoặt'] },
    meaning: {
      en: 'The Wheel marks a turn in the pattern. Conditions shift, chance steps in, and the wise response is to read the timing without pretending to control it all.',
      vi: 'Bánh Xe Số Phận đánh dấu một khúc quanh trong vòng xoay. Hoàn cảnh đổi thay, cơ duyên xuất hiện, và cách ứng xử khôn ngoan là đọc đúng thời điểm thay vì cố nắm giữ mọi thứ.',
    },
    reversedKeywords: { en: ['delays', 'temporary setbacks', 'resisting change'], vi: ['chậm trễ', 'trắc trở tạm thời', 'kháng cự đổi thay'] },
    reversedMeaning: {
      en: 'Reversed, it shows a wheel slowing or a lesson repeating. Loosen your grip on what lies outside your control.',
      vi: 'Khi ngược, lá bài cho thấy vòng xoay đang chậm lại hoặc một bài học cứ lặp lại. Hãy nới lỏng nỗ lực kiểm soát những điều ngoài tầm tay.',
    },
  },
  {
    id: 'justice',
    atlas: 'major',
    atlasIndex: 11,
    group: 'major',
    name: { en: 'Justice', vi: 'Công Lý' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#c9f2e8',
    keywords: { en: ['truth', 'balance', 'accountability'], vi: ['sự thật', 'cân bằng', 'trách nhiệm'] },
    meaning: {
      en: 'Justice brings clarity through balance. It asks what is fair, what is true, and what naturally follows from choices already made.',
      vi: 'Công Lý mang lại sự sáng rõ thông qua cân bằng. Lá bài hỏi điều gì là công bằng, điều gì là thật, và hệ quả nào tất yếu theo sau những lựa chọn đã rồi.',
    },
    reversedKeywords: { en: ['bias', 'avoidance', 'unfairness'], vi: ['thiên vị', 'né tránh', 'bất công'] },
    reversedMeaning: {
      en: 'Reversed, it points to dodged responsibility or a tilted scale. Look the truth in the eye, even when it is hard.',
      vi: 'Khi ngược, lá bài chỉ về việc né tránh trách nhiệm hoặc một cán cân đang nghiêng lệch. Hãy nhìn thẳng vào sự thật, kể cả khi điều đó khó khăn.',
    },
  },
  {
    id: 'the-hanged-man',
    atlas: 'major',
    atlasIndex: 12,
    group: 'major',
    name: { en: 'The Hanged Man', vi: 'Người Bị Treo' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#9ad7ff',
    keywords: { en: ['pause', 'new perspective', 'surrender'], vi: ['tạm dừng', 'góc nhìn mới', 'buông tay'] },
    meaning: {
      en: 'The Hanged Man speaks of a deliberate pause. When you change your point of view, what seemed stuck reveals another way through.',
      vi: 'Người Bị Treo nói về một sự tạm dừng có chủ đích. Khi bạn đổi góc nhìn, điều tưởng như bế tắc bỗng mở ra một lối khác.',
    },
    reversedKeywords: { en: ['stalling', 'feeling stuck', 'resistance'], vi: ['lần lữa', 'mắc kẹt', 'chống cự'] },
    reversedMeaning: {
      en: 'Reversed, it shows prolonged delay or feeling stuck from refusing to release an old view.',
      vi: 'Khi ngược, lá bài cho thấy sự trì hoãn kéo dài hoặc cảm giác mắc kẹt vì không chịu buông một quan điểm cũ.',
    },
  },
  {
    id: 'death',
    atlas: 'major',
    atlasIndex: 13,
    group: 'major',
    name: { en: 'Death', vi: 'Tử Thần' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#c5b4ff',
    keywords: { en: ['endings', 'release', 'transformation'], vi: ['kết thúc', 'buông bỏ', 'chuyển hóa'] },
    meaning: {
      en: 'Death rarely means literal loss; it speaks of necessary endings. Something has outlived its season so a cleaner form can emerge.',
      vi: 'Tử Thần hiếm khi nói về mất mát theo nghĩa đen; nó nói về những kết thúc cần thiết. Một điều đã qua mùa của nó để nhường chỗ cho một hình hài trong trẻo hơn.',
    },
    reversedKeywords: { en: ['clinging', 'fear of change', 'stalled transition'], vi: ['níu kéo', 'sợ đổi thay', 'chuyển tiếp dở dang'] },
    reversedMeaning: {
      en: 'Reversed, it shows holding on to what has already expired. A door only closes fully when you let it.',
      vi: 'Khi ngược, lá bài cho thấy bạn đang níu giữ điều đã hết hạn. Một cánh cửa chỉ thật sự khép lại khi bạn cho phép nó khép.',
    },
  },
  {
    id: 'temperance',
    atlas: 'major',
    atlasIndex: 14,
    group: 'major',
    name: { en: 'Temperance', vi: 'Tiết Độ' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#9ef0df',
    keywords: { en: ['integration', 'healing', 'moderation'], vi: ['dung hòa', 'chữa lành', 'chừng mực'] },
    meaning: {
      en: 'Temperance blends what seemed separate, favoring healing, proportion, gradual alignment, and the patience to let a better mixture form.',
      vi: 'Tiết Độ hòa quyện những điều tưởng như tách biệt, đề cao sự chữa lành, sự cân đối, việc căn chỉnh từ từ và lòng kiên nhẫn để một hỗn hợp tốt đẹp hơn thành hình.',
    },
    reversedKeywords: { en: ['imbalance', 'excess', 'impatience'], vi: ['mất cân bằng', 'quá đà', 'sốt ruột'] },
    reversedMeaning: {
      en: 'Reversed, it points to imbalance or impatience for instant results. Return to a measured rhythm.',
      vi: 'Khi ngược, lá bài chỉ về sự mất cân bằng hoặc nóng lòng muốn có kết quả tức thì. Hãy trở lại một nhịp điệu vừa phải.',
    },
  },
  {
    id: 'the-devil',
    atlas: 'major',
    atlasIndex: 15,
    group: 'major',
    name: { en: 'The Devil', vi: 'Ác Quỷ' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#d98cff',
    keywords: { en: ['attachment', 'temptation', 'dependence'], vi: ['ràng buộc', 'cám dỗ', 'lệ thuộc'] },
    meaning: {
      en: 'The Devil mirrors the invisible cords — habits, fears, or desires that bind you. It invites you to see clearly what you cling to.',
      vi: 'Ác Quỷ phản chiếu những sợi dây vô hình: thói quen, nỗi sợ hay ham muốn đang trói buộc bạn. Lá bài mời bạn nhìn rõ điều mình đang bám víu.',
    },
    reversedKeywords: { en: ['release', 'awareness', 'breaking free'], vi: ['giải thoát', 'nhận ra', 'cắt đứt'] },
    reversedMeaning: {
      en: 'Reversed, it signals awakening and the power to free yourself. You are seeing what once held you.',
      vi: 'Khi ngược, lá bài báo hiệu sự tỉnh thức và khả năng tự cởi trói. Bạn đang nhìn ra điều từng kìm giữ mình.',
    },
  },
  {
    id: 'the-tower',
    atlas: 'major',
    atlasIndex: 16,
    group: 'major',
    name: { en: 'The Tower', vi: 'Tòa Tháp' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#ff8f6b',
    keywords: { en: ['upheaval', 'awakening', 'release'], vi: ['đổ vỡ', 'thức tỉnh', 'giải phóng'] },
    meaning: {
      en: 'The Tower marks the moment an old structure falls so the truth can show. Sudden as it is, it clears space for something more honest.',
      vi: 'Tòa Tháp đánh dấu khoảnh khắc một cấu trúc cũ sụp đổ để sự thật lộ ra. Tuy bất ngờ, nó dọn chỗ cho điều chân thật hơn.',
    },
    reversedKeywords: { en: ['avoiding crisis', 'slow collapse', 'fear of change'], vi: ['né tránh khủng hoảng', 'rạn nứt âm ỉ', 'sợ thay đổi'] },
    reversedMeaning: {
      en: 'Reversed, it shows clinging to something already shaking. Gentle change beats fighting it to the end.',
      vi: 'Khi ngược, lá bài cho thấy bạn đang cố níu giữ điều vốn đã lung lay. Thay đổi nhẹ nhàng vẫn hơn là chống cự đến cùng.',
    },
  },
  {
    id: 'the-star',
    atlas: 'major',
    atlasIndex: 17,
    group: 'major',
    name: { en: 'The Star', vi: 'Ngôi Sao' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#b2ccff',
    keywords: { en: ['hope', 'renewal', 'guidance'], vi: ['hy vọng', 'tái sinh', 'soi đường'] },
    meaning: {
      en: 'The Star is a soft light after strain — hope, perspective, emotional renewal, and a reminder that guidance can be gentle and still be real.',
      vi: 'Ngôi Sao là thứ ánh sáng dịu dàng sau những căng thẳng: niềm hy vọng, góc nhìn rộng mở và lời nhắc rằng sự dẫn lối có thể nhẹ nhàng mà vẫn chân thật.',
    },
    reversedKeywords: { en: ['discouragement', 'lost faith', 'weariness'], vi: ['nản lòng', 'mất niềm tin', 'mỏi mệt'] },
    reversedMeaning: {
      en: 'Reversed, it speaks of a temporary loss of hope. Rest; the light is still there, only dimmed for a while.',
      vi: 'Khi ngược, lá bài nói về sự cạn hy vọng nhất thời. Hãy nghỉ ngơi; ánh sáng vẫn còn đó, chỉ là mờ đi trong chốc lát.',
    },
  },
  {
    id: 'the-moon',
    atlas: 'major',
    atlasIndex: 18,
    group: 'major',
    name: { en: 'The Moon', vi: 'Mặt Trăng' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#d6b5ff',
    keywords: { en: ['dreams', 'uncertainty', 'the subconscious'], vi: ['giấc mơ', 'mơ hồ', 'tiềm thức'] },
    meaning: {
      en: 'The Moon reveals the fog around perception. Honor your feelings without letting fear invent the whole story.',
      vi: 'Mặt Trăng hé lộ lớp sương mờ quanh nhận thức. Hãy tôn trọng cảm xúc của mình mà đừng để nỗi sợ tự dệt nên cả câu chuyện.',
    },
    reversedKeywords: { en: ['clearing confusion', 'untangling', 'relief'], vi: ['dần sáng tỏ', 'gỡ rối', 'nhẹ lòng'] },
    reversedMeaning: {
      en: 'Reversed, the fog is lifting and misunderstandings are untangling. The truth is becoming easier to see.',
      vi: 'Khi ngược, sương mù đang tan và những hiểu lầm dần được gỡ. Sự thật đang trở nên dễ nhìn hơn.',
    },
  },
  {
    id: 'the-sun',
    atlas: 'major',
    atlasIndex: 19,
    group: 'major',
    name: { en: 'The Sun', vi: 'Mặt Trời' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#ffe08a',
    keywords: { en: ['joy', 'clarity', 'vitality'], vi: ['niềm vui', 'sáng rõ', 'sức sống'] },
    meaning: {
      en: 'The Sun brings warmth, visibility, and simple truth. What is healthy can become easier to see and easier to trust.',
      vi: 'Mặt Trời mang đến sự ấm áp, sự tỏ tường và một sự thật giản dị. Điều lành mạnh có thể trở nên dễ thấy hơn và dễ tin hơn.',
    },
    reversedKeywords: { en: ['forced cheer', 'clouded joy', 'delay'], vi: ['vui gượng', 'niềm vui bị che', 'trì hoãn'] },
    reversedMeaning: {
      en: 'Reversed, it reminds you that joy may be temporarily clouded. Seek out the small things that lighten your heart.',
      vi: 'Khi ngược, lá bài nhắc rằng niềm vui có thể đang bị che khuất tạm thời. Hãy tìm lại những điều nhỏ bé khiến lòng bạn nhẹ nhõm.',
    },
  },
  {
    id: 'judgement',
    atlas: 'major',
    atlasIndex: 20,
    group: 'major',
    name: { en: 'Judgement', vi: 'Phán Xét' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#c7e0ff',
    keywords: { en: ['awakening', 'reckoning', 'rebirth'], vi: ['thức tỉnh', 'soi xét', 'tái sinh'] },
    meaning: {
      en: 'Judgement speaks of an inner call: to look back over the journey, forgive what is past, and step into a truer chapter.',
      vi: 'Phán Xét nói về một tiếng gọi từ bên trong: nhìn lại chặng đường đã qua, tha thứ cho quá khứ và bước sang một chương sống chân thật hơn.',
    },
    reversedKeywords: { en: ['self-criticism', 'hesitation', 'ignoring the call'], vi: ['tự trách', 'do dự', 'lờ đi tiếng gọi'] },
    reversedMeaning: {
      en: 'Reversed, it shows harsh self-judgement or hesitation before a needed change. Go easy on yourself.',
      vi: 'Khi ngược, lá bài cho thấy sự tự phán xét khắt khe hoặc sự do dự trước một thay đổi cần thiết. Hãy nhẹ nhàng với chính mình.',
    },
  },
  {
    id: 'the-world',
    atlas: 'major',
    atlasIndex: 21,
    group: 'major',
    name: { en: 'The World', vi: 'Thế Giới' },
    arcana: { en: 'Major Arcana', vi: 'Ẩn Chính' },
    accent: '#a8f0c8',
    keywords: { en: ['completion', 'wholeness', 'arrival'], vi: ['hoàn tất', 'trọn vẹn', 'cập bến'] },
    meaning: {
      en: 'The World marks the completion of a cycle. It celebrates what has ripened and opens the threshold to the next journey.',
      vi: 'Thế Giới đánh dấu sự trọn vẹn của một chu kỳ. Lá bài mừng cho điều đã chín muồi và mở ra ngưỡng cửa cho hành trình kế tiếp.',
    },
    reversedKeywords: { en: ['incompletion', 'loose ends', 'delayed closure'], vi: ['dang dở', 'chưa khép lại', 'trì hoãn kết thúc'] },
    reversedMeaning: {
      en: 'Reversed, it suggests something nearly finished but missing a final step. Allow yourself to close it fully.',
      vi: 'Khi ngược, lá bài gợi về một việc gần hoàn tất nhưng còn thiếu một bước cuối. Hãy cho phép mình khép lại trọn vẹn.',
    },
  },
];
