// Phase A — lazy loader for the Hugging Face tarot corpus (barissglc/tarot).
//
// The normalized JSON artifacts are generated by scripts/pull_hf_tarot.py and
// served as static files from public/arcana/data/. They are fetched on demand
// (never imported), so the ~3.7 MB corpus does NOT inflate the app JS bundle.
//
// Wiring only — Phase A does not change the Arcana reading UI/flow.

export interface HFTarotReading {
  id: number;
  /** Normalized display names, e.g. ["The Sun", "Three of Cups", "Two of Pentacles"]. */
  cards: string[];
  /** Stable slugs, e.g. ["the-sun", "three-of-cups", "two-of-pentacles"]. */
  cardSlugs: string[];
  /** Order-independent key: sorted slugs joined with "|". */
  comboKey: string;
  reading: string;
}

export interface HFTarotIndex {
  meta: {
    source: string;
    rowCount: number;
    uniqueCombos: number;
    uniqueSlugs: number;
  };
  slugs: string[];
  /** Exact three-card combo key -> reading ids. */
  byCombo: Record<string, number[]>;
  /** Single card slug -> reading ids (for overlap-count fallback). */
  bySlug: Record<string, number[]>;
}

const READINGS_URL = '/arcana/data/hf_tarot_readings.json';
const INDEX_URL = '/arcana/data/hf_tarot_index.json';

let corpusPromise: Promise<HFTarotReading[]> | null = null;
let indexPromise: Promise<HFTarotIndex> | null = null;

async function fetchJson<T>(url: string): Promise<T> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Unable to load Arcana corpus (${response.status}): ${url}`);
  }
  return (await response.json()) as T;
}

/** Lazily load + cache the full reading corpus. */
export function loadHFTarotCorpus(): Promise<HFTarotReading[]> {
  if (!corpusPromise) {
    corpusPromise = fetchJson<HFTarotReading[]>(READINGS_URL).catch((error) => {
      corpusPromise = null; // allow retry on transient failure
      throw error;
    });
  }
  return corpusPromise;
}

/** Lazily load + cache the lookup index. */
export function loadHFTarotIndex(): Promise<HFTarotIndex> {
  if (!indexPromise) {
    indexPromise = fetchJson<HFTarotIndex>(INDEX_URL).catch((error) => {
      indexPromise = null;
      throw error;
    });
  }
  return indexPromise;
}

/** Order-independent combo key from three card slugs. */
export function buildComboKey(slugs: string[]): string {
  return [...slugs].sort().join('|');
}

/**
 * Find readings that exactly match a three-card combo (order-independent).
 * Returns reading ids; empty if no exact match exists.
 */
export function findExactCombo(index: HFTarotIndex, slugs: string[]): number[] {
  return index.byCombo[buildComboKey(slugs)] ?? [];
}

export interface FallbackCandidate {
  id: number;
  /** How many of the requested slugs this reading shares (1..3). */
  overlap: number;
}

/**
 * Fallback candidate selection by overlap count: rank readings that share the
 * most cards with the requested combo. Used when no exact combo exists.
 */
export function findFallbackCandidates(
  index: HFTarotIndex,
  slugs: string[],
  limit = 20,
): FallbackCandidate[] {
  const overlapById = new Map<number, number>();

  for (const slug of new Set(slugs)) {
    for (const id of index.bySlug[slug] ?? []) {
      overlapById.set(id, (overlapById.get(id) ?? 0) + 1);
    }
  }

  return [...overlapById.entries()]
    .map(([id, overlap]) => ({ id, overlap }))
    .sort((a, b) => b.overlap - a.overlap || a.id - b.id)
    .slice(0, limit);
}
